import { afterEach, beforeEach, describe, expect, test } from 'vitest';
import { createRequire } from 'node:module';
import { cp, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import * as path from 'node:path';
import * as os from 'node:os';
import sharp from 'sharp';

const require = createRequire(import.meta.url);
const { checkBranding } = require('../../../scripts/check-branding.cjs') as {
  checkBranding: (sourceRoot: string, temporaryParent: string) => Promise<number>;
};
const originals = path.resolve('src/assets/branding');
let fixture: string;

beforeEach(async () => {
  fixture = await mkdtemp(path.join(os.tmpdir(), 'clanker-branding-test-'));
  await cp(originals, fixture, { recursive: true });
});
afterEach(async () => { await rm(fixture, { recursive: true, force: true }); });

// Snapshot every fixture byte, including the source files. Check output is also
// placed here so a leaked temporary directory would change the snapshot.
async function snapshot(directory: string): Promise<Record<string, string>> {
  const files: Record<string, string> = {};
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const target = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      for (const [name, bytes] of Object.entries(await snapshot(target))) {
        files[`${entry.name}/${name}`] = bytes;
      }
    } else files[entry.name] = (await readFile(target)).toString('base64');
  }
  return files;
}

async function expectDrift(message: string) {
  const before = await snapshot(fixture);
  await expect(checkBranding(fixture, fixture)).rejects.toThrow(message);
  expect(await snapshot(fixture)).toEqual(before);
  expect((await readdir(fixture)).some((name) => name.startsWith('clanker-branding-check-'))).toBe(false);
}

describe('branding drift protection', () => {
  test('accepts synchronized assets without modifying any file or leaving temporary output', async () => {
    const before = await snapshot(fixture);
    expect(await checkBranding(fixture, fixture)).toBe(19);
    expect(await snapshot(fixture)).toEqual(before);
    expect((await readdir(fixture)).some((name) => name.startsWith('clanker-branding-check-'))).toBe(false);
  });

  test('rejects canonical source changes when derivatives have not been regenerated', async () => {
    const source = path.join(fixture, 'clanker-app-icon.png');
    const modified = await sharp(source).flop().png().toBuffer();
    await writeFile(source, modified);
    await expectDrift('changed: clanker-app-512.png');
  });

  test('rejects changed generated bytes with actionable instructions', async () => {
    await writeFile(path.join(fixture, 'generated/clanker-app.ico'), 'broken');
    await expectDrift('Run npm run branding:generate');
  });

  test('rejects missing derivatives', async () => {
    await rm(path.join(fixture, 'generated/clanker-ui-18.png'));
    await expectDrift('missing: clanker-ui-18.png');
  });

  test('rejects unexpected derivatives', async () => {
    await writeFile(path.join(fixture, 'generated/obsolete.png'), 'obsolete');
    await expectDrift('unexpected: obsolete.png');
  });

  test('cleans temporary output even when a source cannot be read', async () => {
    await rm(path.join(fixture, 'clanker-ui-icon.png'));
    await expectDrift('clanker-ui-icon.png');
  });
});
