/**
 * IPC Channel Constants — Unit Tests
 *
 * Verifies that every exported constant is a non-empty string and that the
 * canonical ALL_IPC_CHANNELS list contains no duplicates.
 */

import { describe, it, expect } from 'vitest';
import {
  // Settings
  GET_LAST_WORKSPACE,
  GET_SHOW_FASTFETCH,
  SET_SHOW_FASTFETCH,
  GET_AI_COMMIT_SETTINGS,
  SET_AI_COMMIT_ENABLED,
  SET_AI_COMMIT_PROVIDER,
  SET_AI_COMMIT_MODEL,
  GENERATE_COMMIT_MESSAGE,
  OPEN_DIRECTORY_DIALOG,
  READ_DIRECTORY,
  FILE_LIST_DIRECTORY,
  GET_HARNESS_OPTIONS,
  GET_HARNESS_MODELS,
  GET_HARNESS_DEFAULTS,
  SET_HARNESS_DEFAULTS,
  // Terminal
  SPAWN_TERMINAL,
  GET_TERMINAL_BUFFER,
  WRITE_TERMINAL,
  RESIZE_TERMINAL,
  KILL_TERMINAL,
  TERMINAL_CLEANUP_WORKSPACE,
  TERMINAL_READY,
  TERMINAL_DATA,
  TERMINAL_EXIT,
  TERMINAL_RESIZED,
  WRITE_CLIPBOARD,
  // Browser
  BROWSER_SET_BOUNDS,
  BROWSER_HIDE,
  BROWSER_NAVIGATE,
  BROWSER_BACK,
  BROWSER_FORWARD,
  BROWSER_REFRESH,
  BROWSER_STOP,
  BROWSER_DISPOSE_WORKSPACE,
  OPEN_EXTERNAL,
  REVEAL_IN_FILE_MANAGER,
  CAN_GO_BACK,
  CAN_GO_FORWARD,
  BROWSER_URL_UPDATED,
  BROWSER_GET_URL,
  BROWSER_SAVE_URL,
  FIT_ALL_PANES,
  // Git
  GIT_START_POLLING,
  GIT_STOP_POLLING,
  GIT_GET_BRANCH_STATE,
  GIT_GET_OPERATION_STATE,
  GIT_GET_STASHES,
  GIT_GET_HISTORY,
  GIT_GET_DIFF,
  GIT_GET_FILE_DIFF,
  GIT_STAGE,
  GIT_UNSTAGE,
  GIT_COMMIT,
  GIT_CREATE_BRANCH,
  GIT_SWITCH_BRANCH,
  GIT_DELETE_BRANCH,
  GIT_FORCE_DELETE_BRANCH,
  GIT_MERGE_BRANCH,
  GIT_ABORT_OPERATION,
  GIT_STASH,
  GIT_APPLY_STASH,
  GIT_POP_STASH,
  GIT_DROP_STASH,
  GIT_CLEAR_STASHES,
  GIT_REFRESH,
  GIT_INIT,
  GIT_GET_REMOTES,
  GIT_ADD_REMOTE,
  GIT_REMOVE_REMOTE,
  GIT_RENAME_REMOTE,
  GIT_FETCH,
  GIT_PULL,
  GIT_PUSH,
  GIT_STATUS_UPDATE,
  // Window controls
  MINIMIZE_WINDOW,
  TOGGLE_MAXIMIZE_WINDOW,
  CLOSE_WINDOW,
  IS_MAXIMIZED_WINDOW,
  ZOOM_IN_WINDOW,
  ZOOM_OUT_WINDOW,
  RESET_ZOOM_WINDOW,
  // Credentials
  CREDENTIAL_GENERATE_SSH_KEY,
  CREDENTIAL_GET_PUBLIC_KEY,
  CREDENTIAL_DELETE_SSH_KEY,
  CREDENTIAL_CHECK_EXISTS,
  CREDENTIAL_SAVE_PAT,
  CREDENTIAL_GET_PAT,
  CREDENTIAL_DELETE_PAT,
  CREDENTIAL_GET_STATUS,
  CREDENTIAL_GET_GLOBAL_STATUS,
  CREDENTIAL_CONFIGURE_SSH_HOST,
  // VCS
  VCS_GET_CONTEXT,
  VCS_GET_PR_INFO,
  VCS_GET_DEEP_LINKS,
  VCS_GET_DEEP_LINK,
  VCS_OPEN_DEEP_LINK,
  // Editor
  FILE_READ,
  FILE_WRITE,
  FILE_CREATE,
  FILE_DELETE,
  FILE_RENAME,
  FILE_CHANGED,
  FILE_WATCH,
  FILE_UNWATCH,
  // Explorer
  EXPLORER_TREE_CHANGED,
  EXPLORER_START_WATCHING,
  EXPLORER_STOP_WATCHING,
  // Annotation
  ANNOTATION_ENABLE,
  ANNOTATION_DISABLE,
  ANNOTATION_CAPTURE,
  ANNOTATION_GET_STATE,
  ANNOTATION_EXPORT,
  ANNOTATION_CHECK_ESCAPED,
  ANNOTATION_ESCAPE,
  ANNOTATION_TRIGGER_COPY,
  // Session history
  SESSION_DISCOVER,
  SESSION_INVOKE,
  ALL_IPC_CHANNELS,
} from '../../../src/shared/ipcChannels';

const ALL_CHANNELS = [
  // Settings
  GET_LAST_WORKSPACE,
  GET_SHOW_FASTFETCH,
  SET_SHOW_FASTFETCH,
  GET_AI_COMMIT_SETTINGS,
  SET_AI_COMMIT_ENABLED,
  SET_AI_COMMIT_PROVIDER,
  SET_AI_COMMIT_MODEL,
  GENERATE_COMMIT_MESSAGE,
  OPEN_DIRECTORY_DIALOG,
  READ_DIRECTORY,
  FILE_LIST_DIRECTORY,
  GET_HARNESS_OPTIONS,
  GET_HARNESS_MODELS,
  GET_HARNESS_DEFAULTS,
  SET_HARNESS_DEFAULTS,
  // Terminal
  SPAWN_TERMINAL,
  GET_TERMINAL_BUFFER,
  WRITE_TERMINAL,
  RESIZE_TERMINAL,
  KILL_TERMINAL,
  TERMINAL_CLEANUP_WORKSPACE,
  TERMINAL_READY,
  WRITE_CLIPBOARD,
  // Browser
  BROWSER_SET_BOUNDS,
  BROWSER_HIDE,
  BROWSER_NAVIGATE,
  BROWSER_BACK,
  BROWSER_FORWARD,
  BROWSER_REFRESH,
  BROWSER_STOP,
  BROWSER_DISPOSE_WORKSPACE,
  OPEN_EXTERNAL,
  REVEAL_IN_FILE_MANAGER,
  CAN_GO_BACK,
  CAN_GO_FORWARD,
  BROWSER_GET_URL,
  BROWSER_SAVE_URL,
  // Window controls
  MINIMIZE_WINDOW,
  TOGGLE_MAXIMIZE_WINDOW,
  CLOSE_WINDOW,
  IS_MAXIMIZED_WINDOW,
  ZOOM_IN_WINDOW,
  ZOOM_OUT_WINDOW,
  RESET_ZOOM_WINDOW,
  // Git
  GIT_START_POLLING,
  GIT_STOP_POLLING,
  GIT_GET_BRANCH_STATE,
  GIT_GET_OPERATION_STATE,
  GIT_GET_STASHES,
  GIT_GET_HISTORY,
  GIT_GET_DIFF,
  GIT_GET_FILE_DIFF,
  GIT_STAGE,
  GIT_UNSTAGE,
  GIT_COMMIT,
  GIT_CREATE_BRANCH,
  GIT_SWITCH_BRANCH,
  GIT_DELETE_BRANCH,
  GIT_FORCE_DELETE_BRANCH,
  GIT_MERGE_BRANCH,
  GIT_ABORT_OPERATION,
  GIT_STASH,
  GIT_APPLY_STASH,
  GIT_POP_STASH,
  GIT_DROP_STASH,
  GIT_CLEAR_STASHES,
  GIT_REFRESH,
  GIT_INIT,
  GIT_GET_REMOTES,
  GIT_ADD_REMOTE,
  GIT_REMOVE_REMOTE,
  GIT_RENAME_REMOTE,
  GIT_FETCH,
  GIT_PULL,
  GIT_PUSH,
  // Credentials
  CREDENTIAL_GENERATE_SSH_KEY,
  CREDENTIAL_GET_PUBLIC_KEY,
  CREDENTIAL_DELETE_SSH_KEY,
  CREDENTIAL_CHECK_EXISTS,
  CREDENTIAL_SAVE_PAT,
  CREDENTIAL_GET_PAT,
  CREDENTIAL_DELETE_PAT,
  CREDENTIAL_GET_STATUS,
  CREDENTIAL_GET_GLOBAL_STATUS,
  CREDENTIAL_CONFIGURE_SSH_HOST,
  // Terminal events (no corresponding handle call, but part of the protocol)
  TERMINAL_DATA,
  TERMINAL_EXIT,
  TERMINAL_RESIZED,
  // Browser events
  BROWSER_URL_UPDATED,
  FIT_ALL_PANES,
  // Git events
  GIT_STATUS_UPDATE,
  // VCS
  VCS_GET_CONTEXT,
  VCS_GET_PR_INFO,
  VCS_GET_DEEP_LINKS,
  VCS_GET_DEEP_LINK,
  VCS_OPEN_DEEP_LINK,
  // Editor
  FILE_READ,
  FILE_WRITE,
  FILE_CREATE,
  FILE_DELETE,
  FILE_RENAME,
  FILE_CHANGED,
  FILE_WATCH,
  FILE_UNWATCH,
  // Explorer tree auto-refresh
  EXPLORER_TREE_CHANGED,
  EXPLORER_START_WATCHING,
  EXPLORER_STOP_WATCHING,
  // Annotation
  ANNOTATION_ENABLE,
  ANNOTATION_DISABLE,
  ANNOTATION_CAPTURE,
  ANNOTATION_GET_STATE,
  ANNOTATION_EXPORT,
  ANNOTATION_CHECK_ESCAPED,
  ANNOTATION_ESCAPE,
  ANNOTATION_TRIGGER_COPY,
  // Session history
  SESSION_DISCOVER,
  SESSION_INVOKE,
];

describe('ipcChannels', () => {
  describe('each exported constant', () => {
    for (const channel of ALL_CHANNELS) {
      it(`${channel} is a non-empty string`, () => {
        expect(typeof channel).toBe('string');
        expect(channel.length).toBeGreaterThan(0);
      });
    }
  });

  describe('ALL_IPC_CHANNELS', () => {
    it('contains all individual channel constants', () => {
      for (const channel of ALL_CHANNELS) {
        expect(ALL_IPC_CHANNELS).toContain(channel);
      }
    });

    it('has no duplicate channel names', () => {
      const seen = new Set<string>();
      const duplicates: string[] = [];
      for (const channel of ALL_IPC_CHANNELS) {
        if (seen.has(channel)) {
          duplicates.push(channel);
        }
        seen.add(channel);
      }
      expect(duplicates).toHaveLength(0);
    });

    it('matches the count of individual constants', () => {
      expect(ALL_IPC_CHANNELS.length).toBe(ALL_CHANNELS.length);
    });
  });
});
