import { vi } from 'vitest';
import type { FileListDirectoryResult } from '../../src/shared/types/fileExplorer';

export type ElectronApiMock = {
  [K in keyof Window['electronAPI']]: ReturnType<typeof vi.fn>;
};

const createAsyncMock = <T>(result: T) => vi.fn().mockResolvedValue(result);
const defaultFileListDirectoryResult: FileListDirectoryResult = { success: true, entries: [] };

function createElectronApiMock(overrides: Partial<ElectronApiMock> = {}): ElectronApiMock {
  return {
    getAssistants: createAsyncMock({ available: false, settings: { enabled: false, autoStart: false }, service: { state: 'disabled', ownership: null }, assistants: [], surfaces: [] }),
    configureAssistants: vi.fn(async (settings) => ({ ...{ available: false, settings: { enabled: false, autoStart: false }, service: { state: 'disabled', ownership: null }, assistants: [], surfaces: [] }, settings })),
    refreshAssistants: createAsyncMock({ available: false, settings: { enabled: false, autoStart: false }, service: { state: 'disabled', ownership: null }, assistants: [], surfaces: [] }),
    openAssistant: vi.fn().mockResolvedValue({ state: 'open', replay: '' }),
    writeAssistantPty: vi.fn().mockResolvedValue(undefined),
    resizeAssistantPty: vi.fn().mockResolvedValue(undefined),
    onAssistantPtyData: vi.fn(() => () => undefined),
    onAssistantsChanged: vi.fn(() => () => undefined),
    getAppVersion: createAsyncMock('1.0.0'),
    getLastWorkspace: createAsyncMock(''),
    getBaseDirectory: createAsyncMock(''),
    openBaseDirectoryDialog: createAsyncMock(null),
    openDirectoryDialog: createAsyncMock(null),
    readDirectory: createAsyncMock([]),
    fileListDirectory: createAsyncMock(defaultFileListDirectoryResult),
    getAiCommitSettings: createAsyncMock({ enabled: false, provider: 'codex', model: '' }),
    setAiCommitEnabled: createAsyncMock(undefined),
    setAiCommitProvider: createAsyncMock(undefined),
    setAiCommitModel: createAsyncMock(undefined),
    getTheme: createAsyncMock('dark'),
    setTheme: createAsyncMock(undefined),
    getWorkspaceNavigationMode: createAsyncMock('tabs'),
    setWorkspaceNavigationMode: createAsyncMock(undefined),
    getWorkspaceSidebarWidth: createAsyncMock(280),
    getWorkspaceSidebarExpandedWidth: createAsyncMock(280),
    setWorkspaceSidebarWidth: createAsyncMock(undefined),
    getKeybindingOverrides: createAsyncMock({}),
    setKeybindingOverrides: vi.fn(async (overrides: unknown) => ({ success: true, overrides })),
    onBrowserKeybindingCommand: vi.fn(() => () => undefined),
    spawnTerminal: createAsyncMock({ id: 'terminal-1', pid: 1001 }),
    waitRecipeCommand: createAsyncMock({ status: 'started' }),
    getTerminalBuffer: createAsyncMock(''),
    writeTerminal: createAsyncMock({ success: true }),
    getAgentHandoffStatuses: createAsyncMock({ 'term-1': 'ready' }),
    sendAnnotationToAgent: createAsyncMock({ success: true }),
    resizeTerminal: createAsyncMock({ success: true }),
    killTerminal: createAsyncMock({ success: true }),
    cleanupWorkspaceTerminals: createAsyncMock(0),
    onTerminalData: vi.fn(() => () => undefined),
    onTerminalExit: vi.fn(() => () => undefined),
    onAgentAttentionUpdate: vi.fn(() => () => undefined),
    onTerminalResized: vi.fn(() => () => undefined),
    terminalReady: createAsyncMock({ success: true }),
    writeClipboard: createAsyncMock({ success: true }),
    resolveDroppedFilePath: vi.fn(() => ''),
    remotePreviewWatch: createAsyncMock(null),
    remotePreviewGet: createAsyncMock(null),
    remotePreviewStart: createAsyncMock({ success: false, forward: null, error: 'Unavailable' }),
    remotePreviewStop: createAsyncMock(true),
    onRemotePreviewChanged: vi.fn(() => vi.fn()),
    browserHide: createAsyncMock(undefined),
    browserSetBounds: createAsyncMock(undefined),
    browserNavigate: createAsyncMock(true),
    probeRecipePreview: createAsyncMock({ status: 'remote' }),
    browserBack: createAsyncMock(undefined),
    browserForward: createAsyncMock(undefined),
    browserRefresh: createAsyncMock(undefined),
    browserStop: createAsyncMock(undefined),
    browserCreateTab: createAsyncMock({ url: 'https://github.com', title: '' }),
    browserCloseTab: createAsyncMock(true),
    browserSwitchTab: createAsyncMock({ url: 'https://github.com', title: '' }),
    browserActivate: createAsyncMock(true),
    browserMoveTab: createAsyncMock(true),
    browserGetTabs: createAsyncMock([]),
    browserTabNavigate: createAsyncMock(true),
    browserHistoryGet: createAsyncMock([]),
    browserHistoryAdd: createAsyncMock(true),
    browserHistoryClear: createAsyncMock(true),
    browserDisposeWorkspace: createAsyncMock(undefined),
    openExternal: createAsyncMock(true),
    revealInFileManager: createAsyncMock(true),
    canGoBack: createAsyncMock(false),
    canGoForward: createAsyncMock(false),
    minimizeWindow: createAsyncMock(undefined),
    toggleMaximizeWindow: createAsyncMock(undefined),
    closeWindow: createAsyncMock(undefined),
    isMaximizedWindow: createAsyncMock(false),
    zoomInWindow: createAsyncMock(undefined),
    zoomOutWindow: createAsyncMock(undefined),
    resetZoomWindow: createAsyncMock(undefined),
    windowReadyToShow: createAsyncMock(undefined),
    getWindowZoomFactor: vi.fn(() => 1),
    getHarnessOptions: createAsyncMock({}),
    getHarnessModels: createAsyncMock([]),
    getHarnessDefaults: createAsyncMock({
      codex: { model: '', favorites: [], flags: '' },
      opencode: { model: '', favorites: [], flags: '' },
      pi: { model: '', favorites: [], flags: '' },
      omp: { model: '', favorites: [], flags: '' },
      hermes: { model: '', favorites: [], flags: '' },
      claude: { model: '', favorites: [], flags: '' },
      agy: { model: '', favorites: [], flags: '' },
    }),
    setHarnessDefaults: createAsyncMock(undefined),
    onFitAllPanes: vi.fn(() => () => undefined),
    onBrowserUrlUpdated: vi.fn(() => () => undefined),
    gitStartPolling: createAsyncMock(undefined),
    gitStopPolling: createAsyncMock(undefined),
    generateCommitMessage: createAsyncMock({ success: true, message: 'chore: test fixture' }),
    gitStage: createAsyncMock({ success: true }),
    gitUnstage: createAsyncMock({ success: true }),
    gitCommit: createAsyncMock({ success: true }),
    gitGetBranchState: createAsyncMock({ success: true, isRepo: false, currentBranch: null, isDetached: false, branches: [] }),
    gitListWorktrees: createAsyncMock({ success: true, worktrees: [] }),
    gitCreateWorktree: createAsyncMock({ success: false, error: 'Not configured' }),
    registerOpenWorkspace: vi.fn(async (_id: string, path: string, environmentId = 'local') => ({
      success: true, location: { path, environmentId },
    })),
    unregisterOpenWorkspace: createAsyncMock({ success: true }),
    releaseCheckoutContext: createAsyncMock({ success: true }),
    adoptWorktreeCheckoutContext: createAsyncMock({ success: false, error: 'Not configured' }),
    gitInspectWorktree: createAsyncMock({ success: false, error: 'Not configured' }),
    gitRemoveWorktree: createAsyncMock({ success: false, error: 'Not configured' }),
    gitPruneWorktrees: createAsyncMock({ success: false, pruned: [], error: 'Not configured' }),
    gitUnlockWorktree: createAsyncMock({ success: false, error: 'Not configured' }),
    gitGetOperationState: createAsyncMock({ success: true, isRepo: false, inProgress: false, mode: 'none', conflicts: [], message: 'Not a git repository' }),
    gitGetStashes: createAsyncMock([]),
    gitGetHistory: createAsyncMock([]),
    gitGetDiff: createAsyncMock({ success: true, output: '', title: 'Working tree diff' }),
    gitGetFileDiff: createAsyncMock({
      success: true,
      oldContent: '',
      newContent: '',
      oldPath: '',
      newPath: '',
      isBinary: false,
      hasDiff: false,
    }),
    gitCreateBranch: createAsyncMock({ success: true }),
    gitSwitchBranch: createAsyncMock({ success: true }),
    gitDeleteBranch: createAsyncMock({ success: true }),
    gitForceDeleteBranch: createAsyncMock({ success: true }),
    gitMergeBranch: createAsyncMock({ success: true }),
    gitAbortOperation: createAsyncMock({ success: true }),
    gitStash: createAsyncMock({ success: true }),
    gitApplyStash: createAsyncMock({ success: true }),
    gitPopStash: createAsyncMock({ success: true }),
    gitDropStash: createAsyncMock({ success: true }),
    gitClearStashes: createAsyncMock({ success: true }),
    gitRefresh: createAsyncMock(null),
    gitInit: createAsyncMock({ success: true }),
    gitGetRemotes: createAsyncMock({ success: true, remotes: [], provider: 'unknown' }),
    gitAddRemote: createAsyncMock({ success: true }),
    gitRemoveRemote: createAsyncMock({ success: true }),
    gitRenameRemote: createAsyncMock({ success: true }),
    gitFetch: createAsyncMock({ success: true }),
    gitPull: createAsyncMock({ success: true }),
    gitPush: createAsyncMock({ success: true }),
    onGitStatusUpdate: vi.fn(() => () => undefined),

    // Credential management
    credentialGenerateSshKey: createAsyncMock({ success: true, publicKey: 'ssh-ed25519 AAAA...', fingerprint: 'SHA256:...' }),
    credentialGetPublicKey: createAsyncMock({ success: true, publicKey: 'ssh-ed25519 AAAA...' }),
    credentialDeleteSshKey: createAsyncMock({ success: true }),
    credentialCheckExists: createAsyncMock({ exists: false }),
    credentialSavePat: createAsyncMock({ success: true }),
    credentialGetPat: createAsyncMock({ success: false, error: 'No token stored' }),
    credentialDeletePat: createAsyncMock({ success: true }),
    credentialGetStatus: createAsyncMock({ remoteName: 'origin', provider: 'github', hasSshKey: false, hasPat: false, credentialHelper: null }),
    credentialGetGlobalStatus: createAsyncMock({ defaultSshKeyPath: '', hasDefaultSshKey: false, storedPats: [], credentialHelpers: {} }),
    credentialConfigureSshHost: createAsyncMock({ success: true }),

    // VCS Provider Context
    vcsGetContext: createAsyncMock({ success: false, error: 'Not implemented in mock' }),
    vcsGetPrInfo: createAsyncMock({ success: false, error: 'Not implemented in mock' }),
    vcsGetDeepLinks: createAsyncMock([]),
    vcsGetDeepLink: createAsyncMock(null),
    vcsOpenDeepLink: createAsyncMock(true),

    // Editor
    editorReadFile: createAsyncMock({ success: true, content: '' }),
    editorWriteFile: createAsyncMock({ success: true }),
    editorWatchFile: createAsyncMock(undefined),
    remoteFilesWatch: createAsyncMock(true),
    onRemoteFilesChanged: vi.fn(() => () => undefined),
    editorUnwatchFile: createAsyncMock(undefined),
    onFileChanged: vi.fn(() => () => undefined),

    // File Operations
    fileCreate: createAsyncMock({ success: true }),
    fileDelete: createAsyncMock({ success: true }),
    fileRename: createAsyncMock({ success: true }),

    // Explorer tree auto-refresh
    onExplorerTreeChanged: vi.fn(() => () => undefined),
    explorerStartWatching: createAsyncMock(undefined),
    explorerStopWatching: createAsyncMock(undefined),

    // Session history
    discoverSessions: createAsyncMock([]),
    getHarnessUsage: createAsyncMock({ workspaceId: '', entries: [] }),
    listHarnessAccounts: createAsyncMock({ environmentId: 'local', harness: '', managedSupported: true, accounts: [] }),
    selectHarnessAccount: createAsyncMock({ environmentId: 'local', harness: '', managedSupported: true, accounts: [] }),
    startHarnessAccountAdd: createAsyncMock({ flowId: 'flow', state: { status: 'starting' } }),
    reconnectHarnessAccount: createAsyncMock({ flowId: 'flow', state: { status: 'starting' } }),
    cancelHarnessAccountAuth: createAsyncMock(undefined),
    removeHarnessAccount: createAsyncMock({ environmentId: 'local', harness: '', managedSupported: true, accounts: [] }),
    renameHarnessAccount: createAsyncMock({ environmentId: 'local', harness: '', managedSupported: true, accounts: [] }),
    onHarnessAccountAuthState: vi.fn(() => () => undefined),
    invokeSession: createAsyncMock({ id: 'term-session-1', pid: 2001 }),

    // Workspace Recipes
    recipeGetAll: createAsyncMock([]),
    recipeSave: vi.fn(async (recipe) => recipe),
    recipeDelete: createAsyncMock(true),

    // Browser annotation
    annotationEnable: createAsyncMock({ success: true }),
    annotationDisable: createAsyncMock({ success: true }),
    annotationGetState: createAsyncMock({ enabled: false, initialized: false, workspaceId: null, actions: [], overflowed: false }),
    annotationCapture: createAsyncMock({ success: false, error: 'No annotation pending' }),
    annotationExport: createAsyncMock({ success: true }),
    annotationTriggerCopy: createAsyncMock({ success: true }),
    annotationPrepareSend: createAsyncMock({ success: false, error: 'No annotation pending' }),
    annotationCheckEscaped: createAsyncMock(false),
    onAnnotationEscape: vi.fn(() => () => undefined),
    onAnnotationStateChanged: vi.fn(() => () => undefined),

    // SSH Environments
    sshEnvironmentList: createAsyncMock([]),
    sshEnvironmentSave: vi.fn(async (config) => ({ success: true, config })),
    sshEnvironmentDelete: createAsyncMock({ success: true }),
    sshEnvironmentTest: createAsyncMock({ success: true }),
    sshGetHomeDirectory: createAsyncMock({ homePath: '/home/user', initialPath: '/home/user/workspaces' }),
    sshListDirectories: createAsyncMock({ path: '/home/user/workspaces', parentPath: '/home/user', directories: [] }),
    sshCreateDirectory: createAsyncMock({ path: '/home/user/workspaces/new-folder' }),
    getEnvironmentHarnessOptions: createAsyncMock({}),
    getEnvironmentHarnessModels: createAsyncMock([]),
    ...overrides,
  };
}

export function installElectronApiMock(overrides: Partial<ElectronApiMock> = {}): ElectronApiMock {
  const electronApi = createElectronApiMock(overrides);

  if (typeof window !== 'undefined') {
    Object.defineProperty(window, 'electronAPI', {
      value: electronApi,
      configurable: true,
      writable: true,
    });
    return electronApi;
  }

  vi.stubGlobal('window', { electronAPI: electronApi } as unknown as Window & typeof globalThis);
  return electronApi;
}
